---
- name: Deploy Virtual Machine from template in content library with PowerON State
  community.vmware.vmware_content_deploy_template:
    hostname: '{{ vcenter_hostname | mandatory }}'
    username: '{{ vcenter_username | mandatory }}'
    password: '{{ vcenter_password | mandatory }}'
    template: '{{ vm_template | mandatory }}'
    6content_library: '{{ content_library | default(omit) }}'
    datastore: '{{ datastore | mandatory }}'
    folder: '{{ vm_folder }}'
    datacenter: '{{ vm_datacenter | mandatory }}'
    name: '{{ vm_name | mandatory }}'
    state: '{{ vm_state }}'  
  delegate_to: localhost


